### ISSUE TITLE
Build failure on 32-bit ubuntu, probably due to incorrect preprocessor macro cases.

### ISSUE THREAD

**Issue by ekpyron** [Z3Prover/z3#2776]
32-bit builds on ubuntu fail - here's a build log from launchpad:
https://launchpadlibrarian.net/454011446/buildlog_ubuntu-eoan-i386.libz3-static-dev_1%3A4.8.7-0ubuntu1~eoan_BUILDING.txt.gz

The reason is probably a wrong condition in https://github.com/Z3Prover/z3/blob/30e7c225cd510400eacd41d0a83e013b835a8ece/src/util/mpz.cpp#L73 
My guess is that this should actually be
```
#if (defined(_WINDOWS) !defined(_M_ARM) && !defined(_M_ARM64)) || defined(__GNUC__)
```
Or maybe even just
```
#ifdef _trailing_zeros32
```
For ubuntu + gcc a few lines up this is already hit: https://github.com/Z3Prover/z3/blob/30e7c225cd510400eacd41d0a83e013b835a8ece/src/util/mpz.cpp#L57

This causes https://github.com/Z3Prover/z3/blob/30e7c225cd510400eacd41d0a83e013b835a8ece/src/util/mpz.cpp#L76 to conflict with the builtin ``__builtin_ctz(uint32_t)``, which is an error since it is indeed a valid builtin for gcc on 32-bit systems.

**Comment by ekpyron** [comment]
It's probably not an error on 64-bit systems, since in that case the builtin is ``__builtin_ctz(uint64_t)``, so the occurrence in ``mpz.cpp`` ends up as an unused overload.

**Comment by ekpyron** [comment]
Ah, sorry, this is actually already fixed with https://github.com/Z3Prover/z3/issues/2727

**Comment by YamamotoKaderate** [comment]
I don't think it's fixed, i'm experiencing the same issue on raspberry pi zero (32-bit) while building version 4.8.7

**Comment by nunoplopes** [comment]
@YamamotoKaderate can you try latest git and see if the problem is fixed pls?

**Comment by YamamotoKaderate** [comment]
@nunoplopes It's ok for mpz.cpp on master, thank you
