### ISSUE TITLE
qe2 z3str3 assertion violation at ../src/smt/theory_str_mc.cpp Line: 805

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3063]
Hi,
For this formula:
```
(declare-fun a () String)
(assert (= (str.substr a 0 1) ""))
(assert (distinct (str.substr a 1 1) "*"))
(check-sat-using (then qe2 smt))
```
Z3  smt.string_solver=z3str3  throws out an assertion violation:
```
ASSERTION VIOLATION
File: ../src/smt/theory_str_mc.cpp
Line: 805
lhs_chars.size() == rhs_chars.size()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB

```

OS: Ubuntu 18.04
Commit: 1aea0d2

**Comment by mtrberzi** [comment]
Fixed as of #3095

**Comment by zhendongsu** [comment]
Looks like the crash is still triggered (on latest z3 built with "./configure -d" on Ubuntu 18.04): 
```
[667] % z3 smt.string_solver=z3str3 bug3063.smt2 
ASSERTION VIOLATION
File: ../src/smt/theory_str_mc.cpp
Line: 805
lhs_chars.size() == rhs_chars.size()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
a
[668] % 
[668] % cat bug3063.smt2 
(declare-fun a () String)
(assert (= (str.substr a 0 1) ""))
(assert (distinct (str.substr a 1 1) "*"))
(check-sat-using (then qe2 smt))
[669] % 
```
