### ISSUE TITLE
Debug branch: Assertion violation at ../src/math/lp/int_solver.cpp Line: 427

### ISSUE THREAD

**Issue by muchang** [Z3Prover/z3#3331]
Hi,
For this formula:
```
(declare-fun a () Real)  
(declare-fun b () Real) 
(declare-fun c () Real) 
(declare-fun d () Real) 
(declare-fun e () Real)  
(declare-fun f () Real)   
(assert (not (exists ((g Real)) (=>  (xor (and (= (div a (-  g)) 2.0)))   (and (=> (<= 0.0 g b)  (<= (div (* c g) d) e)) (= f 2.0)))))) 
(check-sat)  
```
Z3 debug branch  throws out an assertion violation:
```
ASSERTION VIOLATION
File: ../src/math/lp/int_solver.cpp
Line: 427
lrac.m_r_solver.calc_current_x_is_feasible_include_non_basis() == lrac.m_r_solver.current_x_is_feasible()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
```

OS: Ubuntu 18.04
Commit: d8d0b09

**Comment by levnach** [comment]
Fixed by https://github.com/Z3Prover/z3/commit/07bb7f1faa9afd48db0c33fa412434b96e879574

**Comment by zhendongsu** [comment]
I still see the exact same crash on the latest debug branch commit: 
```
[514] % z3debug bug.smt2 
ASSERTION VIOLATION
File: ../src/math/lp/int_solver.cpp
Line: 427
lrac.m_r_solver.calc_current_x_is_feasible_include_non_basis() == lrac.m_r_solver.current_x_is_feasible()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
a
[515] % 
```
