### ISSUE TITLE
Build failure on s390x with march != zEC12

### ISSUE THREAD

**Issue by LocutusOfBorg** [Z3Prover/z3#4984]
Hello, for some reasons, Ubuntu s390x doesn't default to zEC12, and the package FTBFS
See: 
https://launchpadlibrarian.net/520351419/buildlog_ubuntu-hirsute-s390x.z3_4.8.10-1_BUILDING.txt.gz

Unfortunately from the build log nothing obvious is seen, but doing this:
CXXFLAGS = -march=zEC12
works as a workaround
https://launchpad.net/ubuntu/+source/z3/4.8.10-1ubuntu1/+build/20954530

Do you have any idea?

**Comment by NikolajBjorner** [comment]
There is something obvious:

/usr/bin/ld: ../math/lp/CMakeFiles/lp.dir/nla_core.cpp.o: in function `std::_Function_handler<void (unsigned int, bool, _scoped_interval<dep_intervals>&), nla::core::check_pdd_eq(dd::solver::equation const*)::{lambda(unsigned int, bool, _scoped_interval<dep_intervals>&)#1}>::_M_invoke(std::_Any_data const&, unsigned int&&, bool&&, _scoped_interval<dep_intervals>&)':
./obj-s390x-linux-gnu/src/math/lp/./src/math/lp/nla_core.cpp:1695: undefined reference to `void nla::intervals::set_var_interval<(dep_intervals::with_deps_t)1>(unsigned int, dep_intervals::im_config::interval&)'

**Comment by NikolajBjorner** [comment]
These linking issues are vary between platforms and compilers. They boil down to instantiating certain templates to ensure that object code gets produced. I pushed an attempted fix.

**Comment by LocutusOfBorg** [comment]
```
/<<PKGBUILDDIR>>/src/math/lp/nla_core.cpp: In instantiation of ‘void nla::intervals::set_var_interval(nla::lpvar, nla::intervals::interval&) [with dep_intervals::with_deps_t wd = dep_intervals::with_deps; nla::lpvar = unsigned int; nla::intervals::interval = dep_intervals::im_config::interval]’:
/<<PKGBUILDDIR>>/src/math/lp/nla_core.cpp:1694:74:   required from here
/<<PKGBUILDDIR>>/src/math/lp/nla_core.cpp:1694:74: error: explicit instantiation of ‘void nla::intervals::set_var_interval(nla::lpvar, nla::intervals::interval&) [with dep_intervals::with_deps_t wd = dep_intervals::with_deps; nla::lpvar = unsigned int; nla::intervals::interval = dep_intervals::im_config::interval]’ but no definition available [-fpermissive]
 1694 |         if (deps) m_intervals.set_var_interval<dd::w_dep::with_deps>(j, a);
```
Hello, thanks! However looks like it seems to be still failing...

**Comment by LocutusOfBorg** [comment]
full build here https://launchpadlibrarian.net/521108240/buildlog_ubuntu-hirsute-s390x.z3_4.8.10-1ubuntu3_BUILDING.txt.gz

**Comment by NikolajBjorner** [comment]
The attempted fix broke the build on all platforms but Windows. I don't have a way to test fixes.
Sometimes compilers have bugs too

**Comment by LocutusOfBorg** [comment]
https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/locutusofborg-ppa/+sourcepub/12118257/+listing-archive-extra
true...

**Comment by NikolajBjorner** [comment]
I am a bit unsure how to reproduce the build environment that fails. 
If I can set up a pipeline that reproduces the failures on my side it would be ideal. 
The output seems to suggest you are using a compiler version we are not yet exercising (?).
The main entry-point for pipelines is here:
https://github.com/Z3Prover/z3/blob/master/azure-pipelines.yml
It loads pre-defined environments and also can load pre-published containers. It is limited to mainstream architectures so I doubt s390x. Your latest build failures indicate to be independent of the architecture.
https://github.com/Z3Prover/z3/blob/master/scripts/nightly.yaml contains an instance where we load a container for centos.

**Comment by LocutusOfBorg** [comment]
Hello, but you can easily add s390x to your test architectures I think
https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z

**Comment by NikolajBjorner** [comment]
I will gladly take pull request that updates https://github.com/Z3Prover/z3/blob/master/azure-pipelines.yml.
Travis is also an option if it is low effort and high reward, but Travis use could disappear given that (1) the current Travis scripts are not actively maintained and probably use long deprecated platforms, (2) Travis is evolving and (3) the license terms for using the service at no billing could very well change.
