### ISSUE TITLE
Non-deterministic behaviour of Z3_mk_solver_for_logic python API

### ISSUE THREAD

**Issue by Hook25** [Z3Prover/z3#6034]
In this [issue on pysmt (link)](https://github.com/pysmt/pysmt/issues/465#issuecomment-1099332451) we have identified a possible bug in the `Z3_mk_solver_for_logic` python API. The `z3.z3core.Z3_mk_solver_for_logic` function should throw an exception on failure but sometimes it does not. PySMT relied on this to check if a logic name was implemented in z3 or not.

From my experiments I found out that seldomly the underlying `z3.z3core._lib.Z3_mk_solver_for_logic` function does not set the error code, therefore the wrapper function is unable to detect it and returns a null pointer as described [here (link)](https://github.com/pysmt/pysmt/issues/465#issuecomment-1099332451).

One possible "bodge" solution is to check the error code **and** if the returned pointer is non-0.

PySMT uses z3 version 4.8.7

**Comment by NikolajBjorner** [comment]
I can't fix issues in down-level Z3. Bugs were fixed between 4.8.7 and later that deal with exception handling.

**Comment by Hook25** [comment]
Updating to the last stable release of [z3-4.8.17](https://github.com/Z3Prover/z3/releases/tag/z3-4.8.17) does not fix the problem

**Comment by agurfinkel** [comment]
@Hook25 , can you provide a repro using only Z3 Python API. If I understand correctly, you are claiming that `Z3_mk_solver_for_logic` may return `0` on failure instead of throwing an exception. This later causes a crash in `SolverFor` method in `z3.py`. 

If that is correct, a short repro would be useful to identify and fix the root cause.

**Comment by Hook25** [comment]
The cause of the problem is a race condition on object destructors/error code checking. Every python API that has to check for an error code is subject to this problem.

### Long version: 
Every z3 python API call works like this 
```python
def Z3_...(...):
  call_f(args)          #I will refer to this as call
  check_errcode()  #and to this as check
  return ...
```
Many tracked objects have a destructor that works like this:
```python
def __del__(self):
   [...]
  Z3_dec_ref_counter(...)
```
The underlying C++ API for every python function works like this:
```C
... Z3_api(...){
   ...
  RESET_ERROR_CODE()
  ...
}
```

The bug comes from the fact that between `call` and `check` an object can be finalized by the garbage collector, so consider the following:
```python
import z3
import gc

class Rec:
  def __init__(self, a):
    self.a = a

def k():
  """
  Store a Z3 object in a circularly referenced object
  """
  s = z3.Solver()
  r = Rec(s)
  r.b = r

def other():
  k()
  solver = z3.SolverFor("abc")
  exit(1)

def main():
  while True:
    other()

if __name__ == '__main__':
    main()
```

The previous example will eventually `SIGV`, non deterministically,  every time the garbage collector runs between `call` and `check`. To make this easier to verify add the following to the `main`:

```python
def main():
  gc.disable()
  [...]
```

and force python to call the garbage collector in the Z3_mk_solver_for_logic API like so:

```python
def Z3_mk_solver_for_logic(a0, a1, _elems=Elementaries(_lib.Z3_mk_solver_for_logic)):
  import gc
  r = _elems.f(a0, a1)
  gc.collect()
  _elems.Check(a0)
  return r
```

The program will deterministically crash every time due to SolverFor not catching the failure.

### Solutions
This is according to me a shortcoming of the design of the API. In order to solve this you can either:
- Disable the garbage collector and re-enable it at the beginning and end of each api function
- Assume failure if a null pointer is returned by an api that should not
- Change the design of the API (for example making errors function specific)
