### ISSUE TITLE
Possible(?) soundness bug with integer/real arithmetic

### ISSUE THREAD

**Issue by LeventErkok** [Z3Prover/z3#677]
For this benchmark:

```
(set-logic QF_NIRA)
(set-option :smt.mbqi true)
(set-option :pp.decimal_precision 16)
(set-option :produce-models true)
(define-fun s2 () Real (/ 1.0 1.0))
(define-fun s4 () Real (/ 2.0 1.0))
(define-fun s10 () Real 0.0)
(define-fun s14 () Real (/ 1024.0 1.0))
(define-fun s15 () Real (/ 32768.0 1.0))
(define-fun s19 () Real (/ 1.0 2.0))
(define-fun s36 () Real (/ 1.0 1024.0))
(declare-fun s0 () Real)
(declare-fun s1 () Real)
(assert
   (let ((s3 (<= s2 s0)))
   (let ((s5 (< s0 s4)))
   (let ((s6 (and s3 s5)))
   (let ((s7 (<= s2 s1)))
   (let ((s8 (< s1 s4)))
   (let ((s9 (and s7 s8)))
   (let ((s11 (= s1 s10)))
   (let ((s12 (/ s0 s1)))
   (let ((s13 (ite s11 s10 s12)))
   (let ((s16 (/ s2 s1)))
   (let ((s17 (ite s11 s10 s16)))
   (let ((s18 (* s15 s17)))
   (let ((s20 (+ s18 s19)))
   (let ((s21 (to_int s20)))
   (let ((s22 (to_real s21)))
   (let ((s23 (/ s22 s15)))
   (let ((s24 (* s14 s23)))
   (let ((s25 (/ s0 s4)))
   (let ((s26 (* s24 s25)))
   (let ((s27 (+ s19 s26)))
   (let ((s28 (to_int s27)))
   (let ((s29 (to_real s28)))
   (let ((s30 (to_int s29)))
   (let ((s31 (to_real s30)))
   (let ((s32 (/ s31 s14)))
   (let ((s33 (* s4 s32)))
   (let ((s34 (- s13 s33)))
   (let ((s35 (ite (< s34 0.0) (- s34) s34)))
   (let ((s37 (< s35 s36)))
   (and s6 s9 (not s37))))))))))))))))))))))))))))))))
(check-sat-using qfnra-nlsat)
(get-model)
```

Z3 is producing:

```
sat
(model
  (define-fun s0 () Real
    (/ 513.0 512.0))
  (define-fun s1 () Real
    (/ 3.0 2.0))
)
```

I do believe the benchmark is actually `unsat`, and I did a run by substituting the suggested model as concrete values to the benchmark, upon which Z3 produced `unsat`.

Could this be a Z3 issue? (The benchmark is automatically generated; any chance I might be doing something bogus?)

**Comment by NikolajBjorner** [comment]
Here is a smaller example:

       (set-logic QF_NIRA)
       (declare-const k!2 Int)
       (assert 
          (and
            (>= (to_real k!2) (/ 131075.0 6.0))
           (not (>= (to_real k!2) (/ 131081.0 6.0)))
        ))
        (check-sat)
        (check-sat-using qfnra-nlsat)
        (get-model)

**Comment by NikolajBjorner** [comment]
After fixing the bug, it now produces the answer unknown, but at least the discrepancy that this example exposed should be fixed.

**Comment by LeventErkok** [comment]
@NikolajBjorner Thanks! The "possible" model is still the same in that case (i.e., what `(get-model)` returns after `unknown`.) Which is a bummer.

Am I to understand that Z3 has a complete decision procedure for real-arithmetic, so long as we do not use `to_int`? Can you recommend a different encoding? Essentially I need to compute the floor/ceiling for a real value, so I'm routing through `to_int`. (But I'd be just fine if I were to stay in the real domain, if that's of any help.) Does that make the problem inherently undecidable?

**Comment by NikolajBjorner** [comment]
I guess it is easily seen as undecidable: take a Diophantine constraint, replace each integer by the floor of a real variable of the same name. Sorry. The nlsat tactic is best effort when there are integers. If it finds a model with integers it is happy, or if it establishes unsat. But if the current model is non-integral, then it gives up.

**Comment by LeventErkok** [comment]
Ah, that makes perfect sense! Much appreciated. (Though sad that it didn't work out!)
