### ISSUE TITLE
Performance Issues with Incremental Solving

### ISSUE THREAD

**Issue by AnirudhNarsipur** [Z3Prover/z3#7441]
For a static analysis project, I'm using Z3 4.13.0 through the Python api. I use a combination of theories: arrays, (linear) arithmetic, strings and bitvectors (I was originally using datatypes but noticed better performance representing them as bitvectors).

I need to make repeated queries to the solver to check the current status of the constraints. However, I'm noticing performance blowups for even relatively simple instances. 

This seems to be purely due to incremental solving as opposed to the difficulty of the problems. When I extract out the smtlib2 file from instances that timeout in Python (more than 60 seconds), z3 is able to solve them almost instantly (0.1 s). If I add multiple `(check-sat)` queries to the smtlib file the same instance now takes significantly longer (8s).

I don't use any push/pops and only use assumptions. 

Is there any way I can improve performance here or at the very least get the Python API to be close in performance to directly invoking the solver with a smtlib2 file?

I've attached example smtlib2 files. These are meant purely to illustrate the performance problem and are not minimized.

Thanks!
[singlequery.txt](https://github.com/user-attachments/files/17613041/singlequery.txt)
[multiquery.txt](https://github.com/user-attachments/files/17613042/multiquery.txt)

**Comment by NikolajBjorner** [comment]
It is solved mainly due to pre-processing that eliminates variables from equations.
This is not available in incremental mode for this version. 
It is probably the more common shortcoming of incremental mode that it doesn't include useful variable elimination.

**Comment by AnirudhNarsipur** [comment]
Thanks Nikolaj!

I'm still not sure what the reason for the difference in runtime between Python and command line is. 

Do you have any suggestions for mitigating this?

**Comment by NikolajBjorner** [comment]
instead of using incremental mode, create a solver for every new query.

**Comment by AnirudhNarsipur** [comment]
Thank you!

Could you also shed light on why there is a drastic (one-shot) performance difference between invoking Z3 from the command line vs Python?
